<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefTablesSeeder extends Seeder
{
    /**
     * Seed reference tables that share the `ref_` prefix.
     */
    public function run(): void
    {
        $now = now();

        DB::table('ref_perguruan_tinggi')->upsert([
            [
                'uuid' => '6c3b1a2e-3f06-4ce6-9e3f-5f8b6f4a9a01',
                'nama' => 'Universitas Pembangunan Nasional Veteran Jakarta',
                'nama_singkat' => 'UPN',
                'id_pt' => 'PT-001',
                'alamat' => 'Jl. Ilmiah No. 123, Jakarta',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => '0a7f9626-2390-43a9-82fa-3ab87ff9a27b',
                'nama' => 'Universitas Indonesia',
                'nama_singkat' => 'UI',
                'id_pt' => 'PT-002',
                'alamat' => 'Jl. Samudra Raya No. 45, Surabaya',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => '17d65870-9cb3-49c7-a095-0ebe65a0be43',
                'nama' => 'Institut Teknologi Bandung',
                'nama_singkat' => 'ITB',
                'id_pt' => 'PT-003',
                'alamat' => 'Jl. Angkasa No. 7, Bandung',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['uuid'], ['nama', 'nama_singkat', 'id_pt', 'alamat', 'updated_at']);

        DB::table('ref_skema')->upsert([
            [
                'uuid' => 'c79e1f30-4b3b-4a09-9a25-3e1fde12bd12',
                'jenis_skema' => 'Penelitian',
                'nama' => 'ECOLL: KOLABORASI RISET FKLPPM',
                'nama_singkat' => 'ECOLL',
                'multi_tahun' => true,
                'biaya_minimal' => 60000000,
                'biaya_maksimal' => 80000000,
                'sumber_dana' => 'BKS-PTN-BARAT',
                'anggota_min' => 3,
                'anggota_max' => 5,
                'mulai' => '2025-01-01',
                'selesai' => '2025-12-31',
                'created_at' => $now,
                'created_by' => null,
                'updated_at' => $now,
                'deleted_at' => null,
                'status' => 'aktif',
            ],

            [
                'uuid' => '34de00c7-1a1c-4cc9-8d07-98b236c9d399',
                'jenis_skema' => 'Pengabdian',
                'nama' => 'CS-COLL: KOLABORASI PENGABDIAN KEPADA MASYARAKAT FKLPPM',
                'nama_singkat' => 'CS-COLL',
                'multi_tahun' => false,
                'biaya_minimal' => 40000000,
                'biaya_maksimal' => 60000000,
                'sumber_dana' => 'DRPM',
                'anggota_min' => 2,
                'anggota_max' => 4,
                'mulai' => '2025-03-01',
                'selesai' => '2025-09-30',
                'created_at' => $now,
                'created_by' => null,
                'updated_at' => $now,
                'deleted_at' => null,
                'status' => 'aktif',
            ],
        ], ['uuid'], [
            'jenis_skema',
            'nama',
            'nama_singkat',
            'multi_tahun',
            'biaya_minimal',
            'biaya_maksimal',
            'sumber_dana',
            'anggota_min',
            'anggota_max',
            'mulai',
            'selesai',
            'created_by',
            'updated_at',
            'deleted_at',
            'status',
        ]);

        DB::table('ref_fokus')->upsert([
            [
                'uuid' => 'f4a3b5f7-8c5d-4a71-9b53-6ef620a43112',
                'fokus' => 'Ketahanan Pangan',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'db29f914-cf33-4692-8532-522a0aa96ab6',
                'fokus' => 'Energi',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '9721b041-3a54-4975-80df-b796cf38bcdd',
                'fokus' => 'Gizi dan Kesehatan',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '43f0d331-4d3f-4a67-85c4-124d5418bb61',
                'fokus' => 'Transportasi',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'a3d4c273-0162-49b4-b3c5-c2fdbf822d4a',
                'fokus' => 'Produk Rekayasa Keteknikan',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '8f9a2d7b-3569-4b11-8e7f-1f9a8b8e5f6b',
                'fokus' => 'Pertahanan dan Keamanan',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '6d3a7e21-39cb-40a8-b8a5-ff732cf08ab4',
                'fokus' => 'Kemaritiman',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '2cdb8a1a-2359-4a2c-a7e1-889a1e4b8eab',
                'fokus' => 'Sosial Humaniora',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'fbc1b3a7-51e4-42b3-9a6b-d52d0c6b356c',
                'fokus' => 'Bidang Riset lainnya',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'c8a5b679-d0a8-4a7e-b35d-351fd5f726a9',
                'fokus' => 'Obat Berbahan Alam',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '38b9c247-ff65-4c98-9b93-49b5efc65d41',
                'fokus' => 'Inovasi Sains',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '40ff1ab6-d364-4eb4-b8ce-82d54d7f06e4',
                'fokus' => 'Inovasi teknologi mitigasi bencana',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'a7bcd6c4-b6c5-4f51-8ee8-68b978a8b7a5',
                'fokus' => 'Inovasi teknologi dan industri',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '6b582b79-76c1-4d6a-8121-9a1cbf4b0879',
                'fokus' => 'Pengembangan karakter bangsa',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '8ad57e45-1a25-41b9-bc39-259f3b820d8a',
                'fokus' => 'Ekonomi dan Sumber Daya Manusia',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '1e4b9b1c-42db-4d3d-80a2-5118f37a09bc',
                'fokus' => 'Hukum, politik dan civil society',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'd3173e4a-f07f-45a1-93f1-2db468b19522',
                'fokus' => 'Multidisiplin & Lintas Sektor (Kebencanaan, Biodiversitas, Stunting, Lingkungan, Sumber Daya Air, Iklim)',
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '0b8c3d45-5d68-48f7-9b54-00c8a4b7f42f',
                'fokus' => 'Kesehatan Obat',
                'created_at' => $now,
                'created_by' => null,
            ],
        ], ['uuid'], ['fokus', 'created_by']);

        DB::table('ref_sdg')->upsert([
            [
                'uuid' => 'b02ce966-49b1-4e89-944d-2bb3770a3489',
                'sdg' => 'Tanpa Kemiskinan',
                'level' => 1,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'c9b7a6e1-5374-40e8-a6fc-fc12a81b76db',
                'sdg' => 'Tanpa Kelaparan',
                'level' => 2,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'ad70b7b4-ec76-4a81-9e8c-2fce6b09d83f',
                'sdg' => 'Kehidupan Sehat dan Sejahtera',
                'level' => 3,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '0bc0ed8e-03b6-4f35-adab-b1dfdddcbbc6',
                'sdg' => 'Pendidikan Berkualitas',
                'level' => 4,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '82d65012-7f3b-4d09-bc72-11580a12553e',
                'sdg' => 'Kesetaraan Gender',
                'level' => 5,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'b4d1ab62-1e27-41b2-bf61-f42a63e59162',
                'sdg' => 'Air Bersih dan Sanitasi Layak',
                'level' => 6,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '19d64911-1d9c-48eb-85c4-50dbfad8473c',
                'sdg' => 'Energi Bersih dan Terjangkau',
                'level' => 7,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '64cfd1eb-f8a2-42cf-b59b-3a0f6f5d109f',
                'sdg' => 'Pekerjaan Layak dan Pertumbuhan Ekonomi',
                'level' => 8,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '13d05d1d-f5ce-4b79-8b61-9d1c2d9ed7a3',
                'sdg' => 'Industri, Inovasi dan Infrastruktur',
                'level' => 9,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '442d2f16-bf8c-4b9a-9a09-2b157a4f4efb',
                'sdg' => 'Berkurangnya Kesenjangan',
                'level' => 10,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '0a3b9c76-8c82-4f94-9874-0914a65f78c0',
                'sdg' => 'Kota dan Pemukiman yang Berkelanjutan',
                'level' => 11,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'e1b7f436-87e5-4e54-84xb3-0e3b1830a82d',
                'sdg' => 'Konsumsi dan Produksi yang Bertanggung Jawab',
                'level' => 12,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '09db2a35-d299-4606-b3e8-4127b159b715',
                'sdg' => 'Penanganan Perubahan Iklim',
                'level' => 13,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'b8b7b344-8a12-46d9-936f-9e1a77a6d46c',
                'sdg' => 'Ekosistem Lautan',
                'level' => 14,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'bbbc5e3e-99b4-47f5-b51f-36ce079b06d8',
                'sdg' => 'Ekosistem Daratan',
                'level' => 15,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'c7f42799-d930-42f0-b76b-cb1e45250f62',
                'sdg' => 'Perdamaian, Keadilan dan Kelembagaan yang Tangguh',
                'level' => 16,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'e0f7c6a3-bb9c-4c0b-8a3a-d07f2a4d39a4',
                'sdg' => 'Kemitraan untuk Mencapai Tujuan',
                'level' => 17,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'd69bc7d7-523a-4b9d-8e44-8b7d61e7c831',
                'sdg' => 'Tidak terkait',
                'level' => null,
                'created_at' => $now,
                'created_by' => null,
            ],
        ], ['uuid'], ['sdg', 'level', 'created_by']);

        DB::table('ref_tkt')->upsert([
            [
                'uuid' => 'd1e3a4b1-1bca-4cb3-8c27-1cc11a2b7a01',
                'tkt' => 'Prinsip dasar teknologi / hasil litbang telah dipelajari (diteliti dan dilaporkan).',
                'level' => 1,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '2e17f73b-67a9-4f0b-9487-0459d88a6b11',
                'tkt' => 'Formulasi konsep atau aplikasi teknologi / hasil litbang telah dilakukan.',
                'level' => 2,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'fd3b21a9-0c89-4fe1-85a3-ed3f13d7a2fc',
                'tkt' => 'Telah dilakukan pengujian analitis dan eksperimen untuk membuktikan konsep (proof-of-concept) teknologi / hasil litbang.',
                'level' => 3,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '0a6f5c39-1d0a-4741-9b39-381f31c31e8e',
                'tkt' => 'Validasi kode, komponen (breadboard validation) teknologi / hasil litbang dalam lingkungan laboratorium (terkontrol).',
                'level' => 4,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '7a8c2e5c-9455-4c9e-996a-1ca5bde42a55',
                'tkt' => 'Validasi kode, komponen (breadboard validation) teknologi / hasil litbang dalam lingkungan simulasi.',
                'level' => 5,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'ff61b2ae-1fcb-4927-b2f8-51a2e27c7e5e',
                'tkt' => 'Model atau prototipe sistem/subsistem telah didemonstrasikan/diuji dalam suatu lingkungan yang relevan.',
                'level' => 6,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '3a13cafb-96f5-4e6a-9c83-2852db66b56f',
                'tkt' => 'Model atau prototipe sistem/subsistem telah didemonstrasikan/diuji dalam lingkungan (aplikasi) sebenarnya.',
                'level' => 7,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => 'b4a24b37-3b22-4c92-a9f3-f2046f6d1a81',
                'tkt' => 'Sistem telah lengkap dan memenuhi syarat (qualified) melalui pengujian dalam lingkungan (aplikasi) sebenarnya.',
                'level' => 8,
                'created_at' => $now,
                'created_by' => null,
            ],
            [
                'uuid' => '9fd81a37-3a21-4821-aac6-0b22e2cf3b92',
                'tkt' => 'Sistem teknologi / hasil litbang berhasil (teruji dan terbukti) dalam penggunaan yang dituju (aplikasi sebenarnya).',
                'level' => 9,
                'created_at' => $now,
                'created_by' => null,
            ],
        ], ['uuid'], ['tkt', 'level', 'created_by']);

        DB::table('ref_komponen_rab')->upsert([
            ['id' => 1, 'kategori' => 'PPkM', 'nama' => 'Bahan', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'kategori' => 'PPkM', 'nama' => 'Pengumpulan Data', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'kategori' => 'PPkM', 'nama' => 'Sewa', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'kategori' => 'P', 'nama' => 'Analisis Data', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5, 'kategori' => 'P', 'nama' => 'Pelaporan, Luaran Wajib, dan Luaran Tambahan', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 6, 'kategori' => 'P', 'nama' => 'Honorarium', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 7, 'kategori' => 'PkM', 'nama' => 'Teknologi dan Inovasi Pengabdian', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 8, 'kategori' => 'PkM', 'nama' => 'Biaya Lainnya Pengabdian', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 9, 'kategori' => 'PkM', 'nama' => 'Biaya Updah dan Jasa Pengabdian', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 10, 'kategori' => 'PkM', 'nama' => 'Biaya Pelatihan Pengabdian', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 11, 'kategori' => 'PkM', 'nama' => 'Biaya Perjalanan', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 12, 'kategori' => 'PkM', 'nama' => 'Biaya Upah dan Jasa', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 13, 'kategori' => 'PkM', 'nama' => 'Biaya Pelatihan', 'created_at' => $now, 'updated_at' => $now],
        ], ['id'], ['kategori', 'nama', 'updated_at', 'deleted_at']);

        DB::table('ref_komponen_biaya')->upsert([
            [
                'id' => 1,
                'id_komponen_rab' => 6,
                'jenis' => 'HON',
                'nama_komponen' => 'Honorarium Peneliti',
                'keterangan' => 'Honor untuk ketua dan anggota tim peneliti dalam kegiatan penelitian',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'id_komponen_rab' => 1,
                'jenis' => 'BHN',
                'nama_komponen' => 'Bahan Penelitian',
                'keterangan' => 'Pembelian bahan habis pakai untuk kebutuhan laboratorium dan eksperimen penelitian',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'id_komponen_rab' => 2,
                'jenis' => 'OPS',
                'nama_komponen' => 'Pengumpulan Data Lapangan',
                'keterangan' => 'Biaya transportasi, akomodasi, dan peralatan lapangan dalam proses pengumpulan data penelitian',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'id_komponen_rab' => 4,
                'jenis' => 'ANL',
                'nama_komponen' => 'Analisis Data',
                'keterangan' => 'Biaya untuk pengolahan, analisis, dan interpretasi data hasil penelitian',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'id_komponen_rab' => 5,
                'jenis' => 'LRN',
                'nama_komponen' => 'Pelaporan dan Luaran Penelitian',
                'keterangan' => 'Biaya penyusunan laporan, publikasi jurnal, serta luaran wajib dan tambahan penelitian',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'id_komponen_rab' => 7,
                'jenis' => 'MDK',
                'nama_komponen' => 'Teknologi dan Inovasi Pengabdian',
                'keterangan' => 'Biaya penerapan teknologi dan inovasi untuk kegiatan pengabdian masyarakat',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'id_komponen_rab' => 8,
                'jenis' => 'LNP',
                'nama_komponen' => 'Biaya Lainnya Pengabdian',
                'keterangan' => 'Biaya tidak langsung untuk mendukung kelancaran pelaksanaan kegiatan pengabdian',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'id_komponen_rab' => 9,
                'jenis' => 'JSP',
                'nama_komponen' => 'Upah dan Jasa Pengabdian',
                'keterangan' => 'Biaya upah tenaga kerja atau jasa profesional dalam kegiatan pengabdian masyarakat',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'id_komponen_rab' => 10,
                'jenis' => 'PLT',
                'nama_komponen' => 'Pelatihan Masyarakat',
                'keterangan' => 'Biaya pelatihan, sosialisasi, dan workshop bagi masyarakat dalam kegiatan pengabdian',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'id_komponen_rab' => 11,
                'jenis' => 'PRJ',
                'nama_komponen' => 'Perjalanan Dinas',
                'keterangan' => 'Biaya transportasi, akomodasi, dan konsumsi untuk kegiatan penelitian dan pengabdian di luar kota',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'id_komponen_rab' => 12,
                'jenis' => 'UPJ',
                'nama_komponen' => 'Upah dan Jasa Penunjang',
                'keterangan' => 'Biaya jasa pendukung kegiatan seperti desain, dokumentasi, dan pembuatan media promosi pengabdian',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'id_komponen_rab' => 13,
                'jenis' => 'PLH',
                'nama_komponen' => 'Pelatihan Tambahan',
                'keterangan' => 'Biaya pelatihan tambahan untuk penguatan kapasitas masyarakat atau mitra pengabdian',
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
        ], ['id'], [
            'id_komponen_rab',
            'jenis',
            'nama_komponen',
            'keterangan',
            'updated_at',
            'deleted_at',
        ]);
    }
}
