version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
      target: prod
    image: risetabdimas-app
    container_name: risetabdimas_app
    restart: unless-stopped
    ports:
      - "9090:80"
    env_file:
      - .env.docker
